---
title: "Text Analysis Work"
author: "Noelle & Gael"
date: '2024-04-15'
output: html_document
---
```{r}
install.packages(c("tidyverse", 
                   "tidytext",
                   "stopwords",
                   "widyr",
                   "tidygraph",
                   "tidylo",
                   "ggraph",
                   "wordcloud",
                   "dplyr"))
```


```{r}
library(dplyr)
library(tidyverse)
library("magrittr") 
library(tidyverse)
library(tidytext)
```


```{r}
library(readr)
journal_71_72 <- read_csv("Data_Sets/journal_1871_1872 - Sheet1 (1).csv")
journal_73 <- read_csv("Data_Sets/journal_1873 - Sheet1.csv")
journal_74 <- read_csv("Data_Sets/journal_1874 - Sheet1.csv")
journal_75 <- read_csv("Data_Sets/journal_1875 - Sheet1.csv")
journal_76 <- read_csv("Data_Sets/journal_1876 - Sheet1.csv")
journal_77 <- read_csv("Data_Sets/journal_1877 - Sheet1.csv")
journal_80 <- read_csv("Data_Sets/journal_1880 - Sheet1.csv")
journal_86 <- read_csv("Data_Sets/journal_1886 - Sheet1.csv")
View(journal_1886_Sheet1)

```

```{r}
#journals <- list.files(path = "Data_Sets/...", pattern = "*.csv", full.names = TRUE) %>% 
#  map_df(~read_csv(.x) %>% mutate(quantity = as.character(quantity))) #%>%
#  type_convert()
```

```{r}
journal_71_72$journal <- 1
journal_73$journal <- 2
journal_74$journal <- 3
journal_75$journal <- 4
journal_76$journal <- 5
journal_77$journal <- 6

journal_80$journal <- 9

journal_86$journal <- 15
```

```{r}
journal_71_72 <- journal_71_72 %>%
  rename(transcription_accuracy = transcription) %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description))

journal_75 <- journal_75 %>%
  mutate(quantity = as.character(quantity)) %>%
  mutate(latitude = as.logical(latitude)) %>%
  mutate(latitude_origin = as.logical(latitude_origin)) %>%
  mutate(longitude = as.logical(longitude)) %>%
  mutate(longitude_origin = as.logical(longitude_origin))

journal_76 <- journal_76 %>%
  mutate(quantity = as.character(quantity)) %>%
  mutate(latitude = as.logical(latitude)) %>%
  mutate(latitude_origin = as.logical(latitude_origin)) %>%
  mutate(longitude = as.logical(longitude)) %>%
  mutate(longitude_origin = as.logical(longitude_origin)) %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.logical(noteworthy))

journal_77 <- journal_77 %>%
  mutate(quantity = as.character(quantity)) %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.logical(noteworthy)) %>%
  mutate(temperature_am = as.logical(temperature_am))

journal_80 <- journal_80 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.logical(noteworthy)) %>%
  mutate(temperature_am = as.logical(temperature_am)) %>%
  mutate(temperature_pm = as.logical(temperature_pm)) %>%
  mutate(temperature_night = as.logical(temperature_night))
  
journal_86 <- journal_86 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.logical(noteworthy)) %>%
  mutate(temperature_am = as.logical(temperature_am)) %>%
  mutate(temperature_pm = as.logical(temperature_pm)) %>%
  mutate(temperature_night = as.logical(temperature_night)) %>%
  mutate(latitude = as.logical(latitude)) %>%
  mutate(recorder = as.character(recorder)) %>%
  mutate(notes = as.character(notes)) %>%
  select(- ...37)

  
```



```{r}
#journal_71_72 <-  journal_71_72 %>% mutate(across(.fns = as.character)) %>% type_convert()
#journal_73 <-  journal_73 %>% mutate(across(.fns = as.character)) %>% type_convert()
#journal_74 <-  journal_74 %>% mutate(across(.fns = as.character)) %>% type_convert()
#journal_75 <-  journal_75 %>% mutate(across(.fns = as.character)) %>% type_convert()
#journal_76 <-  journal_76 %>% mutate(across(.fns = as.character)) %>% type_convert()
#journal_77 <-  journal_77 %>% mutate(across(.fns = as.character)) %>% type_convert()
#journal_80 <-  journal_80 %>% mutate(across(.fns = as.character)) %>% type_convert()
#journal_86 <-  journal_86 %>% mutate(across(.fns = as.character)) %>% type_convert()
```

```{r}
journals <- dplyr::bind_rows(journal_71_72, journal_73, journal_74, journal_75, journal_76, journal_77, journal_80, journal_86)
```



# Figure out where Freeland goes locally most often
```{r}
loc_place <- journals %>%
  select(journal, local_place, location) %>%
  separate(local_place, c("place_1", "place_2", "place_3", "place_4"), sep = ",")
```
```{r}
loc_1 <- loc_place %>%
  select(place_1) %>%
  rename(place = place_1)
loc_2 <- loc_place %>%
  select(place_2) %>%
  rename(place = place_2)
loc_3 <- loc_place %>%
  select(place_3) %>%
  rename(place = place_3)
loc_4 <- loc_place %>%
  select(place_4) %>%
  rename(place = place_4)

loc_count <- dplyr::bind_rows(loc_1, loc_2, loc_3, loc_4)
```

```{r}
loc_count <- loc_count %>%
  mutate(place = str_to_title(place)) %>%
  mutate(place = trimws(place, "both")) #str_squish 

```

```{r}
loc_count <- loc_count %>%
    count(place, sort = TRUE)
```



```{r}
loc_count %>%
    filter(n > 30) %>%
    filter(n < 2000) %>% #2000 to get rid of NA (may change)
  ggplot(aes(x=place, y=n)) + 
   geom_bar(stat = "identity")+
    theme(axis.text.x = element_text(angle = 60, hjust = 1))+
   labs(y = "n", x = "Location", title = "Local Locations in Freeland Bunker's Journals")
```


# Frequent words in association with Home
```{r}
library(stringr)

Home <-  dplyr::filter(journals, grepl('Home| home| Home', local_place))

#https://stackoverflow.com/questions/22850026/filter-rows-which-contain-a-certain-string
```
```{r}
(journal_words <- Home %>%
    unnest_tokens(word, journal_entry) %>%
    count(journal, word, sort = TRUE) %>%
    filter(!word %in% stop_words$word))
```
```{r}
journal_tf_idf <- journal_words %>%
    bind_tf_idf(word, journal, n) %>%
    arrange(desc(tf_idf))
```
```{r}
journal_tf_idf %>%
    group_by(journal) %>%
    slice_max(tf_idf, n = 10) %>%
    ggplot(aes(tf_idf, fct_reorder(word, tf_idf), fill = journal)) +
    geom_col(show.legend = FALSE) +
    facet_wrap(vars(journal), scales = "free") +
    scale_x_continuous(expand = c(0,0)) +
    labs(y = NULL, x = "tf-idf", title = "Highest tf-idf words in Freeland Bunker's Journal entries associated with mention of being at home")
```

# Frequent words in association with the Lodge of Good Templars
```{r}
library(stringr)

LoGT <-  dplyr::filter(journals, grepl('Lodge of Good Templars| Lodge of Good Templars| Lodge of  Good Templars|	Lodge of the Good Templars', local_place))

#https://stackoverflow.com/questions/22850026/filter-rows-which-contain-a-certain-string
```
```{r}
(journal_words <- LoGT %>%
    unnest_tokens(word, journal_entry) %>%
    count(journal, word, sort = TRUE) %>%
    filter(!word %in% stop_words$word))
```
```{r}
journal_tf_idf <- journal_words %>%
    bind_tf_idf(word, journal, n) %>%
    arrange(desc(tf_idf))
```
```{r}
journal_tf_idf %>%
    group_by(journal) %>%
    slice_max(tf_idf, n = 10) %>%
    ggplot(aes(tf_idf, fct_reorder(word, tf_idf), fill = journal)) +
    geom_col(show.legend = FALSE) +
    facet_wrap(vars(journal), scales = "free") +
    scale_x_continuous(expand = c(0,0)) +
    labs(y = NULL, x = "tf-idf", title = "Highest tf-idf words in Freeland Bunker's Journal entries associated with mention of being at home")
```


# Frequent words in association with Hall

# Frequent words in association with Shop

# Frequent words in association with Wharf
