---
title: "Text Analysis Work"
author: "Noelle & Gael"
date: '2024-04-15'
output: html_document
---
```{r install-packages}
# install.packages(c("tidyverse", 
#                   "tidytext",
#                   "stopwords",
#                   "widyr",
#                   "tidygraph",
#                   "tidylo",
#                   "ggraph",
 #                  "wordcloud",
  #                 "dplyr", "googlesheets4"))
```


```{r read-in-packages}
library(dplyr)
library(tidyverse)
library(magrittr) 
library(tidyverse)
library(tidytext)
library(googlesheets4)
```


```{r read-in-data}

journal_71_72 <- read_sheet('https://docs.google.com/spreadsheets/d/1f3buvhuRprNvo_2a4TwjgN-Qez0NkLk6d2VBjhsVt5Y/edit?gid=0#gid=0')
journal_73 <- read_sheet('https://docs.google.com/spreadsheets/d/1GwncgtXAYXHKhhLlVi5hquwziiKPLk5DrKGlVX0KVA4/edit?gid=0#gid=0')
journal_74 <- read_sheet('https://docs.google.com/spreadsheets/d/1H-5XqEJOe0adljtb1tQwFKlQ77EEnFWwwzRmvmKwaeE/edit?gid=0#gid=0')
journal_75 <- read_sheet('https://docs.google.com/spreadsheets/d/1Y4fyBjSQfj_lXfmh161NozzQeTnvmMJjNxYBVqCNLEk/edit?gid=0#gid=0')
journal_76 <- read_sheet('https://docs.google.com/spreadsheets/d/1Cw_DZuzm2ouQrNKZiO3s9Xhp5a1S7wnnxYqudWVDmJ8/edit?gid=0#gid=0')
journal_77 <- read_sheet('https://docs.google.com/spreadsheets/d/1u4BYkD_wH6A8bRELL6peXUDM_p3Zfpbd_O2E--zcLto/edit?gid=0#gid=0')
journal_78 <- read_sheet('https://docs.google.com/spreadsheets/d/1kY3BVQAYhlaqtyqcqxXBiA_DCzW_GarF_mzZjyO3CP8/edit?gid=0#gid=0')
journal_79 <- read_sheet('https://docs.google.com/spreadsheets/d/1wKwbIAqf-44KsPcjwrfIlrucUTyAKlZIceZ1lJch4dY/edit?gid=0#gid=0')
journal_80 <- read_sheet('https://docs.google.com/spreadsheets/d/1iBaOKU5jTTZAqm-CdQzyjtLIk5nhtHLzocvZoD6VK6w/edit?gid=0#gid=0')
journal_81 <- read_sheet('https://docs.google.com/spreadsheets/d/1avR2jpBmNMLxeVWhGfAZqhCCFbOnbN4gcst4VkSLuKI/edit?gid=0#gid=0')
journal_82 <- read_sheet('https://docs.google.com/spreadsheets/d/1o4Yi4DNQvdWRcq_d8cYzp9CP_4KKy-9g63FOp8bDBp8/edit?gid=0#gid=0')
journal_83 <- read_sheet('https://docs.google.com/spreadsheets/d/1FVyX19rUMigwXRorfFgxocT5tPOEqIAWgbt1gwjZbv0/edit?gid=0#gid=0')
journal_84 <- read_sheet('https://docs.google.com/spreadsheets/d/1EDmiVyAiORba3rm00NI3cxMCJWZGDhJyC2SKpxx9I_Y/edit?gid=0#gid=0')
journal_85 <- read_sheet('https://docs.google.com/spreadsheets/d/1JBFWlfNKH8T1b6BgstqWtIzQJtIv8WX-RL2rVSdrrPQ/edit?gid=0#gid=0')
journal_86 <- read_sheet('https://docs.google.com/spreadsheets/d/1FGM7h5C-JEg4QdxWTLT-qQMk_F9ssqMHM7NACaEd6D0/edit?gid=0#gid=0')
journal_87 <- read_sheet('https://docs.google.com/spreadsheets/d/1L1wsbbxKNIUEXlqUZVBIHzbgGH9wWbyp0RvFrgODG68/edit?gid=0#gid=0')
journal_88 <- read_sheet('https://docs.google.com/spreadsheets/d/1LS9045UxtPU-wtjX0kqZTG0Cwd0MlWKXm5Je-QbZR-A/edit?gid=0#gid=0')

```

```{r assign-new-column}
journal_71_72$journal <- 1
journal_73$journal <- 2
journal_74$journal <- 3
journal_75$journal <- 4
journal_76$journal <- 5
journal_77$journal <- 6
journal_78$journal <- 7
journal_79$journal <- 8
journal_80$journal <- 9
journal_81$journal <- 10
journal_82$journal <- 11
journal_83$journal <- 12
journal_84$journal <- 13
journal_85$journal <- 14
journal_86$journal <- 15
```

```{r adjust-variable-type}
#in order to join data sets, all the corresponding variables have to match; we glimpse() each dataset and changed variable that didn't match our first one
journal_71_72 <- journal_71_72 %>%
  rename(transcription_accuracy = transcription) %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_73 <- journal_73 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_74 <- journal_74 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 


journal_75 <- journal_75 %>%
  mutate(quantity = as.character(quantity)) %>%
  mutate(latitude_origin = as.character(latitude_origin)) %>%
  mutate(longitude_origin = as.character(longitude_origin)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_76 <- journal_76 %>%
  mutate(quantity = as.character(quantity)) %>%
  mutate(latitude_origin = as.character(latitude_origin)) %>%
  mutate(longitude_origin = as.character(longitude_origin)) %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_77 <- journal_77 %>%
  mutate(quantity = as.character(quantity)) %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_78 <- journal_78 %>%
  mutate(quantity = as.character(quantity)) %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_79 <- journal_79 %>%
  mutate(quantity = as.character(quantity)) %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_80 <- journal_80 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_81 <- journal_81 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(latitude_origin = as.character(latitude_origin)) %>%
  mutate(letter_to = as.character(letter_to)) %>%
  mutate(notes = as.character(notes)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_82 <- journal_82 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(latitude_origin = as.character(latitude_origin)) %>%
  mutate(letter_to = as.character(letter_to))%>%
  mutate(notes = as.character(notes)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_83 <- journal_83 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(latitude_origin = as.character(latitude_origin)) %>%
  mutate(longitude_origin = as.character(longitude_origin)) %>%
  mutate(letter_from = as.character(letter_from)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 
  
journal_84 <- journal_84 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(latitude_origin = as.character(latitude_origin)) %>%
  mutate(letter_to = as.character(letter_to)) %>%
  mutate(notes = as.character(notes)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 

journal_85 <- journal_85 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(weather_condition_night = as.character(weather_condition_night)) %>%
  mutate(latitude_origin = as.character(latitude_origin)) %>%
  mutate(letter_to = as.character(letter_to)) %>%
  mutate(notes = as.character(notes)) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude))) %>%
  mutate(quantity = as.character(quantity)) 

journal_86 <- journal_86 %>%
  mutate(image_path = as.character(image_path)) %>%
  mutate(image_description = as.character(image_description)) %>%
  mutate(noteworthy = as.character(noteworthy)) %>%
  mutate(temperature_am = as.character(temperature_am)) %>%
  mutate(temperature_pm = as.character(temperature_pm)) %>%
  mutate(temperature_night = as.character(temperature_night)) %>%
  mutate(recorder = as.character(recorder)) %>%
  mutate(notes = as.character(notes)) %>%
  select(- ...37) %>%
  mutate(latitude = as.numeric(as.character(latitude))) %>%
  mutate(longitude = as.numeric(as.character(longitude)))  %>%
  mutate(quantity = as.character(quantity)) 


```

```{r join-datasets}
journals <- dplyr::bind_rows(journal_71_72, journal_73, journal_74, journal_75, journal_76, journal_77, journal_78, journal_79, journal_80, journal_81, journal_82, journal_83, journal_84, journal_85, journal_86)
```

# Filter for most mentioned items

```{r filter-out-NA}
items <- journals %>%
  drop_na(item)
```

```{r separate-multiple-items}
#sometimes multiple things are in a list in one entry of a column, we want to separate to be able to count them all individually

item_count <- items %>%
  separate_longer_delim(item, delim = ",")
```

```{r standardize-formatting}
item_count <- item_count %>%
  drop_na(item) %>%
  mutate(item = str_to_title(item)) %>%
  mutate(item = trimws(item, "both"))

```

```{r count-items}
item_count <- item_count %>%
    filter(!item %in% c("Na")) 

item_count %>%
    count(item, sort = TRUE)

```


# Find distributions of when items are mentioned across journals

```{r count-and-filter-each-journal}

item_journal_month_count <- item_count %>%
  mutate(month = month(date_mdy),
         week_day = wday(date_mdy, label = TRUE)) %>%
  group_by(journal, item, month) %>%
  summarize(count = n())

item_journal_wday_count <- item_count %>%
  mutate(month = month(date_mdy),
         week_day = wday(date_mdy, label = TRUE),
         week_day_num = wday(date_mdy),
         year = year(date_mdy)) %>%
  group_by(journal, item, week_day, year) %>%
  summarize(count = n())

item_journal_count <- item_count %>%
  group_by(journal) %>%
  count(item) %>%
  arrange(journal, desc(n))
  
```

```{r}
item_journal_count %>%
  filter(item %in% c("Wood", "Lobster", "Coal", "Bark", "Fish")) %>%
  ggplot(aes(x = journal, y = n, color = item, group = item)) +
  geom_line() +
  geom_point()
```


```{r filter-for-top-items}
count_items <- item_journal_count %>%
filter(item %in% c("Wood", "Lobster", "Coal", "Hay"))

```

```{r bar-chart-item-distribution}
count_items %>%
#  filter(n > 5) %>%
  group_by(journal) %>%
  ggplot(aes(x=item, y=n)) + 
   geom_bar(stat = "identity")+
   facet_wrap(vars(journal))+
    theme(axis.text.x = element_text(angle = 60, hjust = 1))+
   labs(y = "n", x = "item", title = "Distribution of items mentioned across journals")
```

## Look at words associated with journal entries mentioning different items

# Wood
```{r filter-for-wood}
library(stringr)

Wood <-  journals %>%
  filter(str_detect(journal_entry, pattern = "Wood|wood"))

```


```{r separate-out-words-in-entries}
(wood_words <- Wood %>%
    unnest_tokens(word, journal_entry) %>%
    count(journal, word, sort = TRUE) %>%
    filter(!word %in% c(stop_words$word, "wind", "thermometer", "degrees", "west")))
```
```{r find-tfidf}
wood_tf_idf <- wood_words %>%
    bind_tf_idf(word, journal, n) %>%
    arrange(desc(tf_idf))
```
```{r plot-tfidf}
wood_tf_idf %>%
#  filter(tf_idf >= 0.02) %>%
    group_by(journal) %>%
    slice_max(tf_idf, n = 10) %>%
    ggplot(aes(tf_idf, fct_reorder(word, tf_idf), fill = journal)) +
    geom_col(show.legend = FALSE) +
    facet_wrap(vars(journal), scales = "free") +
    scale_x_continuous(expand = c(0,0)) +
    labs(y = NULL, x = "tf-idf", title = "Highest tf-idf words in Freeland Bunker's Journal entries associated with mention of Wood")
```

#Lobster
```{r filter-for-lobster}
library(stringr)

Lobster <-  dplyr::filter(item_, grepl('Lobster', item))

#https://stackoverflow.com/questions/22850026/filter-rows-which-contain-a-certain-string
```
```{r separate-out-words-in-entries}
(lobs_words <- Lobster %>%
    unnest_tokens(word, journal_entry) %>%
    count(journal, word, sort = TRUE) %>%
    filter(!word %in% stop_words$word))
```
```{r find-tfidf}
lobs_tf_idf <- lobs_words %>%
    bind_tf_idf(word, journal, n) %>%
    arrange(desc(tf_idf))
```
```{r plot-tfidf}
lobs_tf_idf %>%
#  filter(tf_idf >= 0.02) %>%
    group_by(journal) %>%
    slice_max(tf_idf, n = 10) %>%
    ggplot(aes(tf_idf, fct_reorder(word, tf_idf), fill = journal)) +
    geom_col(show.legend = FALSE) +
    facet_wrap(vars(journal), scales = "free") +
    scale_x_continuous(expand = c(0,0)) +
    labs(y = NULL, x = "tf-idf", title = "Highest tf-idf words in Freeland Bunker's Journal entries associated with mention of Lobster")
```

#Coal
```{r filter-for-coal}
library(stringr)

Coal <-  dplyr::filter(item_count, grepl('Coal', item))

#https://stackoverflow.com/questions/22850026/filter-rows-which-contain-a-certain-string
```
```{r separate-out-words-in-entries}
(coal_words <- Coal %>%
    unnest_tokens(word, journal_entry) %>%
    count(journal, word, sort = TRUE) %>%
    filter(!word %in% stop_words$word))
```
```{r find-tfidf}
coal_tf_idf <- coal_words %>%
    bind_tf_idf(word, journal, n) %>%
    arrange(desc(tf_idf))
```
```{r plot-tfidf}
coal_tf_idf %>%
#  filter(tf_idf >= 0.02) %>%
    group_by(journal) %>%
    slice_max(tf_idf, n = 10) %>%
    ggplot(aes(tf_idf, fct_reorder(word, tf_idf), fill = journal)) +
    geom_col(show.legend = FALSE) +
    facet_wrap(vars(journal), scales = "free") +
    scale_x_continuous(expand = c(0,0)) +
    labs(y = NULL, x = "tf-idf", title = "Highest tf-idf words in Freeland Bunker's Journal entries associated with mention of Coal")
```


#Hay
```{r filter-for-hay}
library(stringr)

Hay <-  dplyr::filter(item_count, grepl('Hay', item))

#https://stackoverflow.com/questions/22850026/filter-rows-which-contain-a-certain-string
```
```{r separate-out-words-in-entries}
(hay_words <- Hay %>%
    unnest_tokens(word, journal_entry) %>%
    count(journal, word, sort = TRUE) %>%
    filter(!word %in% stop_words$word))
```
```{r find-tfidf}
hay_tf_idf <- hay_words %>%
    bind_tf_idf(word, journal, n) %>%
    arrange(desc(tf_idf))
```
```{r plot-tfidf}
hay_tf_idf %>%
#  filter(tf_idf >= 0.02) %>%
    group_by(journal) %>%
    slice_max(tf_idf, n = 10) %>%
    ggplot(aes(tf_idf, fct_reorder(word, tf_idf), fill = journal)) +
    geom_col(show.legend = FALSE) +
    facet_wrap(vars(journal), scales = "free") +
    scale_x_continuous(expand = c(0,0)) +
    labs(y = NULL, x = "tf-idf", title = "Highest tf-idf words in Freeland Bunker's Journal entries associated with mention of Hay")
```