---
title: "Journals Dataset Preparation"
author: "Laurie Baker"
date: "2024-06-25"
output: html_document
---

```{r install-packages}
# install.packages(c("tidyverse", 
#                   "tidytext",
#                   "stopwords",
#                   "widyr",
#                   "tidygraph",
#                   "tidylo",
#                   "ggraph",
 #                  "wordcloud",
  #                 "dplyr", 
# "googlesheets4", 
#"gargle"))

### Resources to add to trello: https://coa-navigating-change.netlify.app/post/04-week/
```


```{r read-in-packages, message = FALSE}
library(dplyr)
library(tidyverse)
library(magrittr) 
library(tidyverse)
library(tidytext)
library(googlesheets4)
library(gargle)
library(googledrive)
library(readxl)
library(naniar)
```


```{r read-in-data}

# # Either specify the user:
# drive_auth(email = "fleduke27@coa.edu",
#            scopes = "drive.readonly")

gs4_deauth()
gs4_auth(
  scopes = c(
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
  )
)



journal_71_72 <- read_sheet('https://docs.google.com/spreadsheets/d/1f3buvhuRprNvo_2a4TwjgN-Qez0NkLk6d2VBjhsVt5Y/edit?gid=0#gid=0')
journal_73 <- read_sheet('https://docs.google.com/spreadsheets/d/1GwncgtXAYXHKhhLlVi5hquwziiKPLk5DrKGlVX0KVA4/edit?gid=0#gid=0')
journal_74 <- read_sheet('https://docs.google.com/spreadsheets/d/1H-5XqEJOe0adljtb1tQwFKlQ77EEnFWwwzRmvmKwaeE/edit?gid=0#gid=0')
journal_75 <- read_sheet('https://docs.google.com/spreadsheets/d/1Y4fyBjSQfj_lXfmh161NozzQeTnvmMJjNxYBVqCNLEk/edit?gid=0#gid=0')
journal_76 <- read_sheet('https://docs.google.com/spreadsheets/d/1Cw_DZuzm2ouQrNKZiO3s9Xhp5a1S7wnnxYqudWVDmJ8/edit?gid=0#gid=0')
journal_77 <- read_sheet('https://docs.google.com/spreadsheets/d/1u4BYkD_wH6A8bRELL6peXUDM_p3Zfpbd_O2E--zcLto/edit?gid=0#gid=0')
journal_78 <- read_sheet('https://docs.google.com/spreadsheets/d/1kY3BVQAYhlaqtyqcqxXBiA_DCzW_GarF_mzZjyO3CP8/edit?gid=0#gid=0')
journal_79 <- read_sheet('https://docs.google.com/spreadsheets/d/1wKwbIAqf-44KsPcjwrfIlrucUTyAKlZIceZ1lJch4dY/edit?gid=0#gid=0')
journal_80 <- read_sheet('https://docs.google.com/spreadsheets/d/1iBaOKU5jTTZAqm-CdQzyjtLIk5nhtHLzocvZoD6VK6w/edit?gid=0#gid=0')
journal_81 <- read_sheet('https://docs.google.com/spreadsheets/d/1avR2jpBmNMLxeVWhGfAZqhCCFbOnbN4gcst4VkSLuKI/edit?gid=0#gid=0')
journal_82 <- read_sheet('https://docs.google.com/spreadsheets/d/1o4Yi4DNQvdWRcq_d8cYzp9CP_4KKy-9g63FOp8bDBp8/edit?gid=0#gid=0')
journal_83 <- read_sheet('https://docs.google.com/spreadsheets/d/1FVyX19rUMigwXRorfFgxocT5tPOEqIAWgbt1gwjZbv0/edit?gid=0#gid=0')
journal_84 <- read_sheet('https://docs.google.com/spreadsheets/d/1EDmiVyAiORba3rm00NI3cxMCJWZGDhJyC2SKpxx9I_Y/edit?gid=0#gid=0')
journal_85 <- read_sheet('https://docs.google.com/spreadsheets/d/1JBFWlfNKH8T1b6BgstqWtIzQJtIv8WX-RL2rVSdrrPQ/edit?gid=0#gid=0')
journal_86 <- read_sheet('https://docs.google.com/spreadsheets/d/1FGM7h5C-JEg4QdxWTLT-qQMk_F9ssqMHM7NACaEd6D0/edit?gid=0#gid=0')
journal_87 <- read_sheet('https://docs.google.com/spreadsheets/d/1L1wsbbxKNIUEXlqUZVBIHzbgGH9wWbyp0RvFrgODG68/edit?gid=0#gid=0')
journal_88 <- read_sheet('https://docs.google.com/spreadsheets/d/1lRYPXqJN_QTghasyfelmWrECUzqH6WqWje5czYWOCx8/edit?gid=0#gid=0')
journal_89 <- read_sheet('https://docs.google.com/spreadsheets/d/1mrOoYOon7hJqYskRp-1G32RQsPQv-9Lrw4vEYMqe3qE/edit?gid=0#gid=0')
journal_90 <- read_sheet('https://docs.google.com/spreadsheets/d/1vDXm7NjfJzJM6pGBggPZ0UZu419eIlCR2Gf6323SYPo/edit?gid=0#gid=0')
journal_91 <- read_sheet('https://docs.google.com/spreadsheets/d/1Kc559RqmPraFuRnxGgHcp176BDjnnO6YZ_-Z-y87Tgs/edit?gid=0#gid=0')
journal_92 <- read_sheet('https://docs.google.com/spreadsheets/d/1QFxi-iiCfUYwEl223lNhE1__h3OD1HEsme4K-0N6fiM/edit?gid=0#gid=0')
journal_93 <- read_sheet('https://docs.google.com/spreadsheets/d/1MKM3bNG2VyV1MVuK7g0JIEKB1v4N4Pq2f21I9RDHpcI/edit?gid=0#gid=0')
journal_94 <- read_sheet('https://docs.google.com/spreadsheets/d/1jMP3OdoJraDnJv875pxpEXB36MeQK7CDRHgX23tOdts/edit?gid=0#gid=0')
journal_95 <- read_sheet('https://docs.google.com/spreadsheets/d/1yYFq22QYgFd_BJY-fbPF7MZVwVqnAy2qMJP4CGziKAU/edit?gid=0#gid=0')
journal_96 <- read_sheet('https://docs.google.com/spreadsheets/d/1JXfSS-iQmPweeALOaaA9C5AVWuca0R090H4HpKdDG1c/edit?gid=0#gid=0')
journal_97 <- read_sheet('https://docs.google.com/spreadsheets/d/1qcmaVwFN796BMvGRzgUXNMJ2BpdYO1kC1Y1ovQWPaxg/edit?gid=0#gid=0')
```

```{r assign-new-column}
journal_71_72$journal <- 1
journal_73$journal <- 2
journal_74$journal <- 3
journal_75$journal <- 4
journal_76$journal <- 5
journal_77$journal <- 6
journal_78$journal <- 7
journal_79$journal <- 8
journal_80$journal <- 9
journal_81$journal <- 10
journal_82$journal <- 11
journal_83$journal <- 12
journal_84$journal <- 13
journal_85$journal <- 14
journal_86$journal <- 15
journal_87$journal <- 16
journal_88$journal <- 17
journal_89$journal <- 18
journal_90$journal <- 19
journal_91$journal <- 20
journal_92$journal <- 21
journal_93$journal <- 22
journal_94$journal <- 23
journal_95$journal <- 24
journal_96$journal <- 25
journal_97$journal <- 26




```


```{r adjust-variable-type-function}

keep_cols <- c(
  "date_mdy",
  "month",
  "journal_entry",
  "transcription_accuracy",
  "location",
  "location_accuracy",
  "local_place",
  "local_place_accuracy",
  "latitude",
  "latitude_origin",
  "longitude",
  "longitude_origin",
  "quantity",
  "unit",
  "item",
  "letter",
  "letter_from",
  "letter_to",
  "wind_direction_am",
  "wind_direction_pm",
  "wind_direction_night",
  "wind_speed_am",
  "wind_speed_pm",
  "wind_speed_night",
  "weather_condition_am",
  "weather_condition_pm",
  "weather_condition_night",
  "temperature_am",
  "temperature_pm",
  "temperature_night",
  "image_path",
  "image_description",
  "recorder",
  "notes",
  "noteworthy",
  "second_check",
  "journal"
)

clean_journal <- function(df, year) {

  df |>
    # keep only desired columns that exist, in your preferred order
    select(any_of(keep_cols)) |>
    # set types (only for columns that exist)
    mutate(
      across(any_of(c(
        "image_path", "image_description", "quantity",
        "noteworthy", "notes", "recorder",
        "temperature_am", "temperature_pm", "temperature_night",
        "latitude_origin", "longitude_origin",
        "letter_from", "letter_to",
        "weather_condition_night"
      )), as.character),
      across(any_of(c("latitude", "longitude")), ~ as.numeric(as.character(.x)))
    ) |>
    mutate(journal_year = year, .after = date_mdy)
}

journal_71_72 <- clean_journal(journal_71_72, year = 1872)
journal_73 <- clean_journal(journal_73, year = 1873)
journal_74 <- clean_journal(journal_74, year = 1874)
journal_75 <- clean_journal(journal_75, year = 1875)
journal_76 <- clean_journal(journal_76, year = 1876)
journal_77 <- clean_journal(journal_77, year = 1877)
journal_78 <- clean_journal(journal_78, year = 1878)
journal_79 <- clean_journal(journal_79, year = 1879)
journal_80 <- clean_journal(journal_80, year = 1880)
journal_81 <- clean_journal(journal_81, year = 1881)
journal_82 <- clean_journal(journal_82, year = 1882)
journal_83 <- clean_journal(journal_83, year = 1883)
journal_84 <- clean_journal(journal_84, year = 1884)
journal_85 <- clean_journal(journal_85, year = 1885)
journal_86 <- clean_journal(journal_86, year = 1886)
journal_87 <- clean_journal(journal_87, year = 1887)

## Other journals to eventually add
journal_88 <- clean_journal(journal_88, year = 1888)
journal_89 <- clean_journal(journal_89, year = 1889)
journal_90 <- clean_journal(journal_90, year = 1890)
journal_91 <- clean_journal(journal_91, year = 1891)
journal_92 <- clean_journal(journal_92, year = 1892)
journal_93 <- clean_journal(journal_93, year = 1893)
journal_94 <- clean_journal(journal_94, year = 1894)
journal_95 <- clean_journal(journal_95, year = 1895)
journal_96 <- clean_journal(journal_96, year = 1896)
journal_97 <- clean_journal(journal_97, year = 1897)
```


```{r adjust-variable-type, eval = FALSE}
#in order to join data sets, all the corresponding variables have to match; we glimpse() each dataset and changed variable that didn't match our first one
journal_71_72 <- journal_71_72 |>
  rename(transcription_accuracy = transcription) |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_73 <- journal_73 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_74 <- journal_74 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 


journal_75 <- journal_75 |>
  mutate(quantity = as.character(quantity)) |>
  mutate(latitude_origin = as.character(latitude_origin)) |>
  mutate(longitude_origin = as.character(longitude_origin)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_76 <- journal_76 |>
  mutate(quantity = as.character(quantity)) |>
  mutate(latitude_origin = as.character(latitude_origin)) |>
  mutate(longitude_origin = as.character(longitude_origin)) |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_77 <- journal_77 |>
  mutate(quantity = as.character(quantity)) |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_78 <- journal_78 |>
  mutate(quantity = as.character(quantity)) |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_79 <- journal_79 |>
  mutate(quantity = as.character(quantity)) |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_80 <- journal_80 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_81 <- journal_81 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(latitude_origin = as.character(latitude_origin)) |>
  mutate(letter_to = as.character(letter_to)) |>
  mutate(notes = as.character(notes)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_82 <- journal_82 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(latitude_origin = as.character(latitude_origin)) |>
  mutate(letter_to = as.character(letter_to))|>
  mutate(notes = as.character(notes)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_83 <- journal_83 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(latitude_origin = as.character(latitude_origin)) |>
  mutate(longitude_origin = as.character(longitude_origin)) |>
  mutate(letter_from = as.character(letter_from)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 
  
journal_84 <- journal_84 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(latitude_origin = as.character(latitude_origin)) |>
  mutate(letter_to = as.character(letter_to)) |>
  mutate(notes = as.character(notes)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_85 <- journal_85 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(weather_condition_night = as.character(weather_condition_night)) |>
  mutate(latitude_origin = as.character(latitude_origin)) |>
  mutate(letter_to = as.character(letter_to)) |>
  mutate(notes = as.character(notes)) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude))) |>
  mutate(quantity = as.character(quantity)) 

journal_86 <- journal_86 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(recorder = as.character(recorder)) |>
  mutate(notes = as.character(notes)) |>
  select(- ...37) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 

journal_87 <- journal_87 |>
  mutate(image_path = as.character(image_path)) |>
  mutate(image_description = as.character(image_description)) |>
  mutate(noteworthy = as.character(noteworthy)) |>
  mutate(temperature_am = as.character(temperature_am)) |>
  mutate(temperature_pm = as.character(temperature_pm)) |>
  mutate(temperature_night = as.character(temperature_night)) |>
  mutate(recorder = as.character(recorder)) |>
  mutate(notes = as.character(notes)) |>
  select(- ...37) |>
  mutate(latitude = as.numeric(as.character(latitude))) |>
  mutate(longitude = as.numeric(as.character(longitude)))  |>
  mutate(quantity = as.character(quantity)) 


```

```{r join-datasets}
journals <- dplyr::bind_rows(journal_71_72, journal_73, journal_74, journal_75, journal_76, journal_77, journal_78, journal_79, journal_80, journal_81, journal_82, journal_83, journal_84, journal_85, journal_86, .id = "journal")

journals_all <- dplyr::bind_rows(journal_71_72, journal_73, journal_74, journal_75, journal_76, journal_77, journal_78, journal_79, journal_80, journal_81, journal_82, journal_83, journal_84, journal_85, journal_86, journal_87, journal_88, journal_89, journal_90, journal_91, journal_92, journal_93, journal_94, journal_95, journal_96,  journal_97, .id = "journal")

```

```{r}
naniar::vis_miss(journals)
```

```{r check dates}

journals_all |>
  mutate(month_check = lubridate::month(date_mdy, label = TRUE, abbr = FALSE)) |>
  filter(month != month_check) |>
  select(journal, date_mdy, month, month_check)

years_to_check <- journals |>
  mutate(year_check = lubridate::year(date_mdy)) |>
  filter(year_check < 1870 | year_check > 1997 | year_check != journal_year) |>
  distinct(year_check, journal_year)

journals_all |>
  mutate(year_check = lubridate::year(date_mdy)) |>
  mutate(year = lubridate::year(date_mdy)) |>
  filter(year %in% year_check) |>
  select(journal, date_mdy, month)

```



```{r write file}
write_csv(journals, file = "data/journals.csv")
write_csv(journals_all, file = "data/journals_all.csv")

```

